In [3]:
pip install numpy pandas


[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.7 MB 1.6 MB/s eta 0:00:06
   ------ --------------------------------- 1.6/9.7 MB 2.2 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.7 MB 2.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.7 MB 3.1 MB/s eta 0:00:03
   ---------------- ----------------------- 3.9/9.7 MB 3.1 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.7 MB 3.2 MB/s eta 0:00:02
   ----------------- ---------------------- 4.2/9.7 MB 3.2 MB/s eta 0:00:02
   ----------------------------- ---------- 7.1/9.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------- ----- 8.

In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [5]:
tf.__version__

'2.20.0'

In [6]:
data = pd.read_csv('cardio_train1.csv')


In [7]:
data['age'] = data['age'] // 365

In [8]:
data.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0


In [9]:
data.isna().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [10]:
X = data.iloc[:, 1:-1]
y = data.iloc[:, -1]

In [11]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X = mms.fit_transform(X)

In [12]:
X

array([[0.6       , 1.        , 0.57948718, ..., 0.        , 0.        ,
        1.        ],
       [0.74285714, 0.        , 0.51794872, ..., 0.        , 0.        ,
        1.        ],
       [0.62857143, 0.        , 0.56410256, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.65714286, 1.        , 0.65641026, ..., 0.        , 1.        ,
        0.        ],
       [0.91428571, 0.        , 0.55384615, ..., 0.        , 0.        ,
        0.        ],
       [0.77142857, 0.        , 0.58974359, ..., 0.        , 0.        ,
        1.        ]])

In [13]:
np.shape(X)

(70000, 11)

In [14]:
y = pd.get_dummies(y)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33123)

In [53]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(11, activation='relu', input_shape=(11,)),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])

c:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │           360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            62 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 554 (2.16 KB)

 Trainable params: 554 (2.16 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
from tensorflow.keras.utils import plot_model
plot_model(model, show_layer_activations=True, show_shapes=True)

You must install pydot (`pip install pydot`) for `plot_model` to work.


In [22]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.CategoricalCrossentropy(), metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [23]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), batch_size=100)

Epoch 1/10
525/525 ━━━━━━━━━━━━━━━━━━━━ 22s 20ms/step - categorical_accuracy: 0.5936 - loss: 0.6595 - val_categorical_accuracy: 0.6314 - val_loss: 0.6416
Epoch 2/10
525/525 ━━━━━━━━━━━━━━━━━━━━ 24s 26ms/step - categorical_accuracy: 0.6387 - loss: 0.6345 - val_categorical_accuracy: 0.6360 - val_loss: 0.6365
Epoch 3/10
525/525 ━━━━━━━━━━━━━━━━━━━━ 18s 19ms/step - categorical_accuracy: 0.6419 - loss: 0.6311 - val_categorical_accuracy: 0.6376 - val_loss: 0.6350
Epoch 4/10
525/525 ━━━━━━━━━━━━━━━━━━━━ 9s 16ms/step - categorical_accuracy: 0.6435 - loss: 0.6292 - val_categorical_accuracy: 0.6426 - val_loss: 0.6318
Epoch 5/10
525/525 ━━━━━━━━━━━━━━━━━━━━ 9s 18ms/step - categorical_accuracy: 0.6454 - loss: 0.6279 - val_categorical_accuracy: 0.6381 - val_loss: 0.6341
Epoch 6/10
525/525 ━━━━━━━━━━━━━━━━━━━━ 11s 17ms/step - categorical_accuracy: 0.6480 - loss: 0.6269 - val_categorical_accuracy: 0.6423 - val_loss: 0.6303
Epoch 7/10
525/525 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - categorical_accuracy: 0

In [24]:
from sklearn.ensemble import RandomForestClassifier
yr = data.iloc[:, -1]

In [25]:
np.unique(yr, return_counts=True)

(array([0, 1]), array([35021, 34979]))

In [26]:
rfc = RandomForestClassifier(n_estimators=200)
Xr_train, Xr_test, yr_train, yr_test = train_test_split(X, yr, random_state=33123)

In [27]:
rfc.fit(Xr_train, yr_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",200
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [28]:
from sklearn.metrics import classification_report

In [29]:
y_pred = rfc.predict(Xr_test)
print(classification_report(y_true=yr_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.70      0.71      0.71      8652
           1       0.71      0.71      0.71      8848

    accuracy                           0.71     17500
   macro avg       0.71      0.71      0.71     17500
weighted avg       0.71      0.71      0.71     17500



In [30]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(11, activation='relu', input_shape=(11,)),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(60, activation='relu'),
    tf.keras.layers.Dense(25, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.CategoricalCrossentropy(), metrics=[tf.keras.metrics.CategoricalAccuracy()])

c:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [36]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 30)             │           360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 60)             │         1,860 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 25)             │         1,525 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 2)              │            52 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,929 (15.35 KB)

 Trainable params: 3,929 (15.35 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test), batch_size=100)

Epoch 1/50
525/525 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - categorical_accuracy: 0.6215 - loss: 0.6487 - val_categorical_accuracy: 0.6289 - val_loss: 0.6406
Epoch 2/50
525/525 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - categorical_accuracy: 0.6373 - loss: 0.6342 - val_categorical_accuracy: 0.6377 - val_loss: 0.6357
Epoch 3/50
525/525 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - categorical_accuracy: 0.6413 - loss: 0.6308 - val_categorical_accuracy: 0.6429 - val_loss: 0.6323
Epoch 4/50
525/525 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - categorical_accuracy: 0.6452 - loss: 0.6288 - val_categorical_accuracy: 0.6407 - val_loss: 0.6325
Epoch 5/50
525/525 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - categorical_accuracy: 0.6472 - loss: 0.6273 - val_categorical_accuracy: 0.6326 - val_loss: 0.6424
Epoch 6/50
525/525 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - categorical_accuracy: 0.6473 - loss: 0.6266 - val_categorical_accuracy: 0.6449 - val_loss: 0.6284
Epoch 7/50
525/525 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - categorical_accuracy: 0.6

In [38]:
model.predict(X_test)[3]

547/547 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step


array([0.2597197 , 0.74028033], dtype=float32)

In [39]:
np.argmax(model.predict(X_test)[3])

547/547 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step


np.int64(1)

In [40]:
y_pred = np.argmax(model.predict(Xr_test), axis=1)
print(classification_report(y_true=yr_test, y_pred=y_pred))

547/547 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step
              precision    recall  f1-score   support

           0       0.72      0.69      0.71      8652
           1       0.71      0.74      0.73      8848

    accuracy                           0.72     17500
   macro avg       0.72      0.72      0.72     17500
weighted avg       0.72      0.72      0.72     17500



In [28]:
# MasoudKaviani.ir